CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    email VARCHAR(255) UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(255) NOT NULL
);

CREATE TABLE servico (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255),
    descricao VARCHAR(255),
    duracao_em_minutos INTEGER,
    profissional_id BIGINT NOT NULL,
    FOREIGN KEY (profissional_id) REFERENCES users(id)
);

CREATE TABLE disponibilidade (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    profissional_id BIGINT NOT NULL,
    dia_da_semana VARCHAR(255) NOT NULL,
    hora_inicio TIME,
    hora_fim TIME,
    FOREIGN KEY (profissional_id) REFERENCES users(id)
);

CREATE TABLE agendamento (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cliente_id BIGINT NOT NULL,
    profissional_id BIGINT NOT NULL,
    servico_id BIGINT NOT NULL,
    data_hora_inicio TIMESTAMP,
    data_hora_fim TIMESTAMP,
    status VARCHAR(255) NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES users(id),
    FOREIGN KEY (profissional_id) REFERENCES users(id),
    FOREIGN KEY (servico_id) REFERENCES servico(id)
); 